package a1351040;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 17 22:30:58 ICT 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 7;
  public static final int DIVIDE = 9;
  public static final int EOF = 0;
  public static final int PLUS = 6;
  public static final int DOUBLELITERAL = 5;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int STRINGLITERAL = 4;
  public static final int TIMES = 8;
  public static final int INTLITERAL = 3;
}

